import sys

username = 'USERNAME HERE'
password = 'PASSWORD HERE'
playlist_uri = 'PLAYLIST URI HERE'
spotconnect_device_name = 'DEVICE NAME HERE'

SP_CLIENT_ID = 'SPOTIFY CLIENT ID HERE'
SP_CLIENT_SECRET = 'SPOTIFY CLIENT SECRET HERE'
SP_REDIRECT_URI = 'SPOTIFY REDIRECT URI HERE'
